{% set name = "stratify" %}
{% set version = "0.4.0" %}

package:
  name: python-stratify
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 582f6fac7e829a11a75f96424284816f4913f1453a90d5b7869df17ecddd1ec1

build:
  skip: true  # [py<311]
  number: 2
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython >=3.1.0                         # [build_platform != target_platform]
    - numpy >=2                              # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - numpy >=2
    - cython >=3.1.0
    - setuptools-scm >=8
    - setuptools >=77.3.0
  run:
    - python
    - cython >=3.1.0
    # dask[array] is dask+numpy, so core is fine here.
    - dask-core >=2025.7.0

test:
  imports:
    - stratify

about:
  home: https://github.com/SciTools-incubator/python-stratify
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Vectorized interpolators that are especially useful for Nd vertical interpolation/stratification of atmospheric and oceanographic datasets.

extra:
  recipe-maintainers:
    - bjlittle
    - cpelley
    - lbdreyer
    - ocefpaf
    - pelson
    - HGWright
