{% set version = "0.2.0" %}

package:
  name: python-stratify
  version: {{ version }}

source:
  url: https://github.com/SciTools-incubator/python-stratify/archive/v{{ version }}.tar.gz
  sha256: 52395a3d4ff92b153fd887b3a20b5e8399d864a13a1b1d5bc9ef674a853a7525

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - numpy
    - cython
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - cython

test:
  imports:
    - stratify

about:
  home: https://github.com/SciTools-incubator/python-stratify
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Vectorized interpolators that are especially useful for Nd vertical interpolation/stratification of atmospheric and oceanographic datasets.

extra:
  recipe-maintainers:
    - bjlittle
    - cpelley
    - lbdreyer
    - ocefpaf
    - pelson
