{% set name = "stratify" %}
{% set version = "0.2.post0" %}

package:
  name: python-stratify
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: baa6c1134cd31635badbf9789cf8898f9fb77dc6e0b5aac51f0deaa5c8b63083

build:
  skip: true  # [win or py<38]
  number: 3
  script: {{ PYTHON }} -m pip install --no-deps .

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - numpy
    - cython
    - setuptools-scm
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - stratify

about:
  home: https://github.com/SciTools-incubator/python-stratify
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Vectorized interpolators that are especially useful for Nd vertical interpolation/stratification of atmospheric and oceanographic datasets.'

extra:
  recipe-maintainers:
    - bjlittle
    - cpelley
    - lbdreyer
    - ocefpaf
    - pelson
