{% set version = "0.1.1" %}

package:
  name: python-stratify
  version: {{ version }}

source:
  url: https://github.com/SciTools-incubator/python-stratify/archive/v{{ version }}.tar.gz
  sha256: 261d7ad413542392d5f897c9751db6583a850e686e311aeef57a6e298b37b30e

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - numpy
    - cython
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - stratify

about:
  home: https://github.com/SciTools-incubator/python-stratify
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Vectorized interpolators that are especially useful for Nd vertical interpolation/stratification of atmospheric and oceanographic datasets.'

extra:
  recipe-maintainers:
    - bjlittle
    - cpelley
    - lbdreyer
    - ocefpaf
    - pelson
